export enum TestType { MOTION, FORM_FIXED, FORM_RANDOM }
export enum Direction { LEFT = 0, RIGHT = 1, RANDOM }
export enum WorldState { PAUSED, RUNNING, FINISHED, TRIAL_CORRECT, TRIAL_INCORRECT, PATCH_SELECTED }